#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
cd $CWD

INSTALL_DIR="$HOME/.local/share/System Information"

mkdir --parents "$INSTALL_DIR"
cp --recursive main/ "$INSTALL_DIR"

# shell script to execute main application
cp ./system-info "$INSTALL_DIR"

# uninstaller
cp ./uninstall-system-info "$INSTALL_DIR"

{
  echo "# systemInfoStart"
  echo "export PATH=\"$PATH:$INSTALL_DIR\""
  echo "# systemInfoEnd"
} >> ~/.bashrc
